name: pr-closed
concurrency: ${{ github.event.number }}

on: 
  pull_request:
    types: [closed]

permissions:
  id-token: write
  contents: read

env:
  resourceGroupName: pr_bicep_${{ github.event.number }}

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v2
        name: Sign in to Azure
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: Azure/cli@v2
        name: Delete resource group
        with: 
          inlineScript: |
            az group delete \
              --name ${{ env.resourceGroupName }} \
              --yes