name: deploy-toy-website
concurrency: toy-company

on: 
  push:
    branches: 
      - main
    paths: 
      - 'toy-sample/deploy/**'
  workflow_dispatch:


env:
    AZURE_RESOURCEGROUP_NAME: ToyWebsite
    ENVIRONMENT: nonprod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: ./toy-sample/deploy/main.bicep
        parameters: environmentType=${{ env.ENVIRONMENT }}